### Check Home Page
GET http://localhost:8080/

### Get Users
GET localhost:8080/users

### Get Users
GET localhost:8080/users/1

### Try to add new user with post
POST localhost:8080/add-user HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Content-Type: application/json

{
  "username" : "hansenssss",
  "password" : "secret-password-99",
  "email" : "email-scret@hansen.nooss"
}

### Fetch users to check if new user add was complete
GET localhost:8080/users

### Try to add new form
POST localhost:8080/forms HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Content-Type: application/json

{
  "username" : "hansenssss",
  "password" : "secret-password-99",
  "email" : "email-scret@hansen.nooss"
}